spring.application.name=authentication-system


# H2 DB
spring.datasource.url=jdbc:h2:file:./data/authdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=test
spring.datasource.password=test

# JPA HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 CONSOLE
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT

jwt.secret=your-super-secret-key-change-this-in-production
jwt.access-expiration=900000
jwt.refresh-expiration=604800000
